# Generated by Django 2.2.4 on 2020-07-09 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_contact_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='users',
        ),
    ]
