# Generated by Django 2.2.4 on 2020-07-12 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200712_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='users',
        ),
    ]
