# Generated by Django 2.2.4 on 2020-07-12 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_orderupdate_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderupdate',
            name='info',
        ),
    ]
